set(TOOLCHAIN Linux_AARCH64)

set(CMAKE_${lang}_COMPILE_OPTIONS_SYSROOT "--sysroot=")

set(ARCH aarch64)

if(DEFINED ENV{AARCH64_LINUX_GNU_TARGET})
    set(AARCH64_LINUX_GNU_TARGET $ENV{AARCH64_LINUX_GNU_TARGET})
else()
    set(AARCH64_LINUX_GNU_TARGET /opt/aarch64/aarch64-linux-gnu-7.3.1)
endif()

set(CMAKE_C_COMPILER ${AARCH64_LINUX_GNU_TARGET}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_C_COMPILER_TARGET ${ARCH})
set(CMAKE_CXX_COMPILER ${AARCH64_LINUX_GNU_TARGET}/bin/aarch64-linux-gnu-g++)
set(CMAKE_CXX_COMPILER_TARGET ${ARCH})

set(CMAKE_FIND_ROOT_PATH ${AARCH64_LINUX_GNU_TARGET}/aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

set(CMAKE_SYSTEM_NAME Linux)
set(TARGET_SYSTEM Linux)